[package]
name = "test_game"
version = "0.1.0"
authors = []

[dependencies]
rand = "0.5"
noise = "0.5"
serde = "1"
serde_derive = "1"

[dependencies.amethyst]
version = "0.9.0"
features = ["nightly"]
